export default {
    title: 'Education',
    data: [
        {
            school: 'Unimelb',
            schoolFull: 'The University of Melbourne',
            college: 'Faculty of Engineering and Information Technology',
            logo: './school/Unimelb.jpeg',
            startDate: '2021-02',
            graduationDate: '2024-12',
            degree: 'Bachelor of Science',
            major: 'Computer Science',
            minor: '',
        },
        {
            school: 'Uconn',
            schoolFull: 'University of Connecticut',
            college: 'College of Computer Engineering',
            logo: './school/Uconn.png',
            startDate: '2023-08',
            graduationDate: '2023-12',
            degree: 'Exchange Program',
            major: 'Computer Science',
            minor: '',
        },
        {
            school: 'PKU',
            schoolFull: 'Peking University',
            college: 'College of Engineering',
            logo: './school/PKU.png',
            startDate: '2023-6',
            graduationDate: '2023-07',
            degree: 'Exchange Program',
            major: 'Computer Science',
            minor: '',
        },
    ],
    status: 0,
}
